pybullet build time: Jul 14 2023 15:41:31
rm: cannot remove 'brain*.nndf': No such file or directory
rm: cannot remove 'fitness*.txt': No such file or directory
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f407f7b8dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f7ed4334dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f7f66b9cdc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7fd580a34dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7fccdee34dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7fdc8f608dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f19b7334dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f1c08058dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f6103404dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f2eff458dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f278e30cdc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f72ccf00dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7fbf99004dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f249ca34dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f1943d00dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f05bdc0cdc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7ff6deb40dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f5881c58dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7fa965c04dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f897ff34dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f6153d34dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f1429640dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7fc8a6d68dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f0ba9534dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7fc88ff64dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f09ae158dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7fbded4a0dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f5a25ca0dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7fdd43b9cdc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f20edc80dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7fe1415b4dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7fd971064dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7fb2f1458dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f2856684dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f1100c58dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7fce0509cdc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.

578.9854513385691
Remaining: 1
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
pybullet build time: Jul 14 2023 15:41:31
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f2275620dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f6116628dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f9f8cc3cdc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7ff2c52ecdc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f0da33d8dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f3a70b58dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f2e640bcdc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f608b904dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f2014198dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f861fa64dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7fd0af534dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f1632124dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f5647954dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f0598e34dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f87684b0dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f6106104dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7ff60b5c4dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7fc4495e4dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f6b82e40dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f908c878dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7fa3f8b40dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f34e4304dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7ff99ac58dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f5e942e4dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f5138208dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7fb6a2a58dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f2efc650dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f8388858dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f405cc34dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f411dc34dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f6e2fb10dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7fd9c4808dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7ff2c2238dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7fcfbc79cdc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f34892c4dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7fc03e590dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
Exception ignored in: <function OpenALDriver.__del__ at 0x7f332c250dc0>
Traceback (most recent call last):
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 27, in __del__
    self.delete()
  File "/home/eertle/.local/lib/python3.10/site-packages/pyglet/media/drivers/openal/adaptation.py", line 34, in delete
    self.worker.stop()
AttributeError: 'OpenALDriver' object has no attribute 'worker'
b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.

578.9854513385691
Remaining: 0
Data saved to bestRuns/100sols_2gens/run96/brain39.nndf
Data saved to bestRuns/100sols_2gens/run96/data/age_fitness_values.npy
pybullet build time: Jul 14 2023 15:41:31
b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:
expected a world element, continuing without it.Data saved to bestRuns/100sols_2gens/run96/data/FrontLower_sensor_values.npy
Data saved to bestRuns/100sols_2gens/run96/data/BackLower_sensor_values.npy
Data saved to bestRuns/100sols_2gens/run96/data/LeftLower_sensor_values.npy
Data saved to bestRuns/100sols_2gens/run96/data/RightLower_sensor_values.npy
Data saved to bestRuns/100sols_2gens/run96/data/metronome_sensor_values.npy
pybullet build time: Jul 14 2023 15:41:31
startThreads creating 1 threads.
starting thread 0
started thread 0 
argc=2
argv[0] = --unused
argv[1] = --start_demo_name=Physics Server
ExampleBrowserThreadFunc started
X11 functions dynamically loaded using dlopen/dlsym OK!
X11 functions dynamically loaded using dlopen/dlsym OK!
Creating context
Created GL 3.3 context
Direct GLX rendering context obtained
Making context current
GL_VENDOR=Microsoft Corporation
GL_RENDERER=D3D12 (NVIDIA Quadro RTX 5000)
GL_VERSION=4.2 (Core Profile) Mesa 22.2.5-0ubuntu0.1~22.04.3
GL_SHADING_LANGUAGE_VERSION=4.20
pthread_getconcurrency()=0
Version = 4.2 (Core Profile) Mesa 22.2.5-0ubuntu0.1~22.04.3
Vendor = Microsoft Corporation
Renderer = D3D12 (NVIDIA Quadro RTX 5000)
b3Printf: Selected demo: Physics Server
startThreads creating 1 threads.
starting thread 0
started thread 0 
MotionThreadFunc thread started
ven = Microsoft Corporation
ven = Microsoft Corporation
b3Printf: b3Warning[examples/Importers/ImportURDFDemo/BulletUrdfImporter.cpp,126]:

b3Printf: expected a world element, continuing without it.
